development:
  adapter: postgresql
  encoding: unicode
  database: projetclem_development
  pool: 5
  username: guilefebvre
  password: Archives51%%

test:
  adapter: postgresql
  encoding: unicode
  database: projetclem_test
  pool: 5
  username: guilefebvre
  password: Archives51%%